version: "3"

services:
  app:
    image: sonarqube:7.9.1-community
    container_name: sonarqube_app
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=$MY_POSTGRES_USER
      - SONARQUBE_JDBC_PASSWORD=$MY_POSTGRES_PASSWORD
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      # - "9092:9092"
    volumes:
      - sq_conf:/opt/sonarqube/conf
      - sq_data:/opt/sonarqube/data
      # - sq_logs:/opt/sonarqube/logs
      - sq_extensions:/opt/sonarqube/extensions
      - sq_plugins:/opt/sonarqube/lib/bundled-plugins
    networks: 
      - sonarqube_net

  db:
    image: postgres:11.5
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$MY_POSTGRES_USER
      - POSTGRES_PASSWORD=$MY_POSTGRES_PASSWORD
      - POSTGRES_DB=sonarqube
    # ports:
    #   - "5432:5432"
    volumes:
      - pg_root:/var/lib/postgresql      
      - pg_data:/var/lib/postgresql/data
    networks: 
      - sonarqube_net

networks:
  sonarqube_net:
    driver: bridge

volumes:
  pg_root:
  pg_data:
  sq_conf:
  sq_data:  
  #sq_logs:
  sq_extensions:
  sq_plugins:
