name: Test Icon-Font-Generator

on:
  push:
    # branches:
    #   - master
    # paths:
    #   - Icon-Font-Generator/**

env:
  ASSETS_SVG_DIR: assets/svg
  ASSETS_3RDPARTY_DIR: assets/3rdParty
  ASSETS_3RDPARTY_CSS_DIR: $ASSETS_3RDPARTY_DIR/css
  ASSETS_3RDPARTY_FONTS_DIR: $ASSETS_3RDPARTY_DIR/webfonts

jobs:
  test-webfont-generation:

    # container:
    #   image: node:14.16

    runs-on: ubuntu-latest
  
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2

      - name: Create Folders
        run: |
          mkdir -p $ASSETS_SVG_DIR
          mkdir -p $ASSETS_3RDPARTY_DIR
          mkdir -p $ASSETS_3RDPARTY_CSS_DIR
          mkdir -p $ASSETS_3RDPARTY_FONTS_DIR

      # https://docs.github.com/en/actions/guides/building-and-testing-nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install fontawesome via npm
        run: npm install --save-dev @fortawesome/fontawesome-free

      - name: Copy files from node_modules to 3rdParty
        run: |
          cp node_modules/@fortawesome/fontawesome-free/webfonts/*.* "$ASSETS_3RDPARTY_FONTS_DIR/"
          cp node_modules/@fortawesome/fontawesome-free/css/brands.min.css "$ASSETS_3RDPARTY_CSS_DIR/fa-brands.min.css"
          cp node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css "$ASSETS_3RDPARTY_CSS_DIR/fa-fontawesome.min.css"
          cp node_modules/@fortawesome/fontawesome-free/css/solid.min.css "$ASSETS_3RDPARTY_CSS_DIR/fa-solid.min.css"

      - name: Copy SVGs from fontawesome (BRANDS)
        run: |
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/facebook.svg $ASSETS_SVG_DIR/fa-brands-facebook.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/github.svg $ASSETS_SVG_DIR/fa-brands-github.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/gitlab.svg $ASSETS_SVG_DIR/fa-brands-gitlab.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/instagram.svg $ASSETS_SVG_DIR/fa-brands-instagram.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/stack-overflow.svg $ASSETS_SVG_DIR/fa-brands-stack-overflow.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/twitter.svg $ASSETS_SVG_DIR/fa-brands-twitter.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/whatsapp.svg $ASSETS_SVG_DIR/fa-brands-whatsapp.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/brands/wordpress.svg $ASSETS_SVG_DIR/fa-brands-wordpress.svg

      - name: Copy SVGs from fontawesome (SOLID)
        run: |
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-down.svg $ASSETS_SVG_DIR/fa-solid-arrow-down.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-up.svg $ASSETS_SVG_DIR/fa-solid-arrow-up.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-circle-down.svg $ASSETS_SVG_DIR/fa-solid-arrow-circle-down.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-circle-up.svg $ASSETS_SVG_DIR/fa-solid-arrow-circle-up.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/asterisk.svg $ASSETS_SVG_DIR/fa-solid-asterisk.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/at.svg $ASSETS_SVG_DIR/fa-solid-at.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/balance-scale.svg $ASSETS_SVG_DIR/fa-solid-balance-scale.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/bars.svg $ASSETS_SVG_DIR/fa-solid-bars.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/chart-line.svg $ASSETS_SVG_DIR/fa-solid-chart-line.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/clock.svg $ASSETS_SVG_DIR/fa-solid-clock.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/cloud.svg $ASSETS_SVG_DIR/fa-solid-cloud.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/cog.svg $ASSETS_SVG_DIR/fa-solid-cog.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/comment-dots.svg $ASSETS_SVG_DIR/fa-solid-comment-dots.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/edit.svg $ASSETS_SVG_DIR/fa-solid-edit.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/envelope.svg $ASSETS_SVG_DIR/fa-solid-envelope.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/envelope-open-text.svg $ASSETS_SVG_DIR/fa-solid-envelope-open-text.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/eye.svg $ASSETS_SVG_DIR/fa-solid-eye.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/globe.svg $ASSETS_SVG_DIR/fa-solid-globe.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/industry.svg $ASSETS_SVG_DIR/fa-solid-industry.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/info.svg $ASSETS_SVG_DIR/fa-solid-info.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/layer-group.svg $ASSETS_SVG_DIR/fa-solid-layer-group.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/mobile.svg $ASSETS_SVG_DIR/fa-solid-mobile.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/phone.svg $ASSETS_SVG_DIR/fa-solid-phone.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/rss.svg $ASSETS_SVG_DIR/fa-solid-rss.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/share-alt.svg $ASSETS_SVG_DIR/fa-solid-share-alt.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/search.svg $ASSETS_SVG_DIR/fa-solid-search.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/search-minus.svg $ASSETS_SVG_DIR/fa-solid-search-minus.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/tags.svg $ASSETS_SVG_DIR/fa-solid-tags.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/thumbs-down.svg $ASSETS_SVG_DIR/fa-solid-thumbs-down.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/thumbs-up.svg $ASSETS_SVG_DIR/fa-solid-thumbs-up.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/user.svg $ASSETS_SVG_DIR/fa-solid-user.svg
          cp ./node_modules/@fortawesome/fontawesome-free/svgs/solid/user-secret.svg $ASSETS_SVG_DIR/fa-solid-user-secret.svg

      - name: Install Iconfinder SVGs
        run: |
          curl https://www.iconfinder.com/icons/4691238/download/svg/512 --output $ASSETS_SVG_DIR/iconfinder-jekyll.svg
          
      - name: Install Icons from Wikipedia
        run: |
          curl https://upload.wikimedia.org/wikipedia/commons/2/25/NuGet_project_logo.svg --output $ASSETS_SVG_DIR/nuget.svg